### ISSUE TITLE
Killing Subprocess during training 

### ISSUE THREAD

**Issue by vishakhalall** [SysCV/sam-hq#63]
I am running into issues while training on a single GPU. I have already tried running with `--device cpu` to ensure it's not a device issue. I don't see any errors, it just kills the subprocess.

Command
```
python3 -m torch.distributed.launch --nproc_per_node=1 train.py --checkpoint ./pretrained_checkpoint/sam_vit_l_0b3195.pth --model-type vit_l --output work_dirs/hq_sam_l  --batch_size_train=1
```

```
HQ Decoder init from SAM MaskDecoder
world size: 1, rank: 0, local rank: 0
{
  "SHELL": "/bin/bash",
  "SESSION_MANAGER": "local/vishakhalall:@/tmp/.ICE-unix/1540,unix/vishakhalall:/tmp/.ICE-unix/1540",
  "QT_ACCESSIBILITY": "1",
  "COLORTERM": "truecolor",
  "XDG_CONFIG_DIRS": "/etc/xdg/xdg-ubuntu:/etc/xdg",
  "XDG_MENU_PREFIX": "gnome-",
  "GNOME_DESKTOP_SESSION_ID": "this-is-deprecated",
  "CONDA_EXE": "/home/vishakhalall/anaconda3/bin/conda",
  "_CE_M": "",
  "LANGUAGE": "en_IN:en",
  "GNOME_SHELL_SESSION_MODE": "ubuntu",
  "SSH_AUTH_SOCK": "/run/user/1001/keyring/ssh",
  "XMODIFIERS": "@im=ibus",
  "DESKTOP_SESSION": "ubuntu",
  "SSH_AGENT_PID": "1416",
  "GTK_MODULES": "gail:atk-bridge",
  "DBUS_STARTER_BUS_TYPE": "session",
  "PWD": "/home/vishakhalall/Documents/SunflowerDepth/sam-hq/train",
  "LOGNAME": "vishakhalall",
  "XDG_SESSION_DESKTOP": "ubuntu",
  "XDG_SESSION_TYPE": "x11",
  "CONDA_PREFIX": "/home/vishakhalall/anaconda3",
  "GPG_AGENT_INFO": "/run/user/1001/gnupg/S.gpg-agent:0:1",
  "XAUTHORITY": "/run/user/1001/gdm/Xauthority",
  "WINDOWPATH": "2",
  "HOME": "/home/vishakhalall",
  "USERNAME": "vishakhalall",
  "IM_CONFIG_PHASE": "1",
  "LANG": "en_IN",
  "LS_COLORS": "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:",
  "XDG_CURRENT_DESKTOP": "ubuntu:GNOME",
  "VTE_VERSION": "6003",
  "CONDA_PROMPT_MODIFIER": "(base) ",
  "GNOME_TERMINAL_SCREEN": "/org/gnome/Terminal/screen/d4f4c326_2382_46dc_bdca_6829eb53e3b1",
  "INVOCATION_ID": "ba44575008b24698be8d04773c16c94f",
  "MANAGERPID": "1013",
  "LESSCLOSE": "/usr/bin/lesspipe %s %s",
  "XDG_SESSION_CLASS": "user",
  "TERM": "xterm-256color",
  "_CE_CONDA": "",
  "LESSOPEN": "| /usr/bin/lesspipe %s",
  "USER": "vishakhalall",
  "CUDA_PATH": "/usr",
  "GNOME_TERMINAL_SERVICE": ":1.114",
  "CONDA_SHLVL": "1",
  "DISPLAY": ":0",
  "SHLVL": "1",
  "QT_IM_MODULE": "ibus",
  "DBUS_STARTER_ADDRESS": "unix:path=/run/user/1001/bus,guid=04f6148d160f766e72e66f8564d48caf",
  "CONDA_PYTHON_EXE": "/home/vishakhalall/anaconda3/bin/python",
  "XDG_RUNTIME_DIR": "/run/user/1001",
  "CONDA_DEFAULT_ENV": "base",
  "JOURNAL_STREAM": "8:49385",
  "XDG_DATA_DIRS": "/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop",
  "PATH": "/home/vishakhalall/anaconda3/bin:/home/vishakhalall/anaconda3/condabin:/home/vishakhalall/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin",
  "GDMSESSION": "ubuntu",
  "DBUS_SESSION_BUS_ADDRESS": "unix:path=/run/user/1001/bus,guid=04f6148d160f766e72e66f8564d48caf",
  "_": "/usr/bin/python3.9",
  "MASTER_ADDR": "127.0.0.1",
  "MASTER_PORT": "29500",
  "WORLD_SIZE": "1",
  "RANK": "0",
  "LOCAL_RANK": "0",
  "QT_QPA_PLATFORM_PLUGIN_PATH": "/home/vishakhalall/.local/lib/python3.9/site-packages/cv2/qt/plugins",
  "QT_QPA_FONTDIR": "/home/vishakhalall/.local/lib/python3.9/site-packages/cv2/qt/fonts",
  "LD_LIBRARY_PATH": "/home/vishakhalall/.local/lib/python3.9/site-packages/cv2/../../lib64:"
}
world_size:1 rank:0 local_rank:0
| distributed init (rank 0): env://
Before torch.distributed.barrier()
End torch.distributed.barrier()
world size: 1
rank: 0
local_rank: 0
args: Namespace(output='work_dirs/hq_sam_l', model_type='vit_l', checkpoint='./pretrained_checkpoint/sam_vit_l_0b3195.pth', device='cuda', seed=42, learning_rate=0.001, start_epoch=0, lr_drop_epoch=10, max_epoch_num=12, input_size=[1024, 1024], batch_size_train=1, batch_size_valid=1, model_save_fre=1, world_size=1, dist_url='env://', rank=0, local_rank=0, find_unused_params=False, eval=False, visualize=False, restore_model=None, gpu=0, distributed=True, dist_backend='nccl')

--- create training dataloader ---
------------------------------ train --------------------------------
--->>> train  dataset  0 / 1   fr-syngenta-1906-2206-2023-train <<<---
-im- fr-syngenta-1906-2206-2023-train /home/vishakhalall/Documents/SunflowerDepth/ExtractedImages/train/images :  0
-gt- fr-syngenta-1906-2206-2023-train /home/vishakhalall/Documents/SunflowerDepth/ExtractedImages/train/mask :  0
0  train dataloaders created
--- create valid dataloader ---
------------------------------ valid --------------------------------
--->>> valid  dataset  0 / 1   fr-syngenta-1906-2206-2023-val <<<---
-im- fr-syngenta-1906-2206-2023-val /home/vishakhalall/Documents/SunflowerDepth/ExtractedImages/val/images :  0
-gt- fr-syngenta-1906-2206-2023-val /home/vishakhalall/Documents/SunflowerDepth/ExtractedImages/val/mask :  0
1  valid dataloaders created
--- define optimizer ---
Killing subprocess 847318
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vishakhalall/.local/lib/python3.9/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/vishakhalall/.local/lib/python3.9/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/vishakhalall/.local/lib/python3.9/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3.9', '-u', 'train.py', '--local_rank=0', '--checkpoint', './pretrained_checkpoint/sam_vit_l_0b3195.pth', '--model-type', 'vit_l', '--output', 'work_dirs/hq_sam_l', '--batch_size_train=1']' died with <Signals.SIGKILL: 9>.

```

**Comment by ymq2017** [comment]
Hi, it looks like there is no image in your folder.  Could you check your training set path or format?

**Comment by vishakhalall** [comment]
Ah yes, I fixed that later, but this issue was due to out of memory errors, I tried increasing the swap memory to fix this issue. Figured this out by monitoring the memory stats.
