### ISSUE TITLE
Performing batch image detection using a for loop can lead to memory leakage.

### ISSUE THREAD

**Issue by morestart** [SysCV/sam-hq#69]
```python
masks, scores, logits = predictor.predict_torch(
            point_coords=input_point,
            point_labels=input_label,
            boxes=transformed_box,
            multimask_output=False,
            hq_token_only=False,
        )
```

error

```
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    masks, num_masks = seg(image, boxes)
  File "samHQ.py", line 39, in __call__
    masks, scores, logits = self.predictor.predict_torch(
```
just process 2 images, raise this error:
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 720.00 MiB (GPU 0; 4.00 GiB total capacity; 2.91 GiB already allocated; 0 bytes free; 3.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```

With the utilization of the CPU, it is feasible to process all the images comprehensively.

**Comment by morestart** [comment]
```python
masks, scores, logits = predictor.predict_torch(
            point_coords=input_point,
            point_labels=input_label,
            boxes=transformed_box,
            multimask_output=False,
            hq_token_only=False,
        )
```

error

```
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    masks, num_masks = seg(image, boxes)
  File "samHQ.py", line 39, in __call__
    masks, scores, logits = self.predictor.predict_torch(
```
just process 2 images, raise this error:
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 720.00 MiB (GPU 0; 4.00 GiB total capacity; 2.91 GiB already allocated; 0 bytes free; 3.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```

**Comment by thangngoc89** [comment]
It's not memory leaks. 4GB is barely enough for 1 image with multiple prompts. The more boxes/points you input for each image, the more RAM it requires. Try to predict_torch with less inputs.

**Comment by morestart** [comment]
sure, i will try
