### ISSUE TITLE
Error when trying to load embedding image in browser using onnx

### ISSUE THREAD

**Issue by moneyhotspring** [SysCV/sam-hq#70]
Error: input 'interm_embeddings' is missing in 'feeds'.
    at d.run (ort.min.js:6:1)
    at runONNX (App.tsx:118:1)
    at App.tsx:96:1
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24931:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)
    at commitPassiveMountEffects (react-dom.development.js:24866:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:1)
    at flushPassiveEffects (react-dom.development.js:26984:1)

**Comment by crapthings** [comment]
i've tried the original sam exporting, its working.
but same process to export onnx doesn't work with official react demo.

i think maybe its in different form?

<img width="1567" alt="image" src="https://github.com/SysCV/sam-hq/assets/1147704/1416e2e6-4b04-4b3c-bf29-3c5d4a88cae1">

**Comment by crapthings** [comment]
<img width="869" alt="image" src="https://github.com/SysCV/sam-hq/assets/1147704/75862292-1f3c-461e-9711-845308d14701">

its working
